// packages/wc-design/src/button/demos/status.ts
import { html } from 'lit';
import '../index.ts';
import '../../space';

export const SuccessDemo = () => html`<wc-space>
  <wc-button status="success">Default</wc-button>
  <wc-button type="primary" status="success">Primary</wc-button>
  <wc-button type="plain" status="success">Plain</wc-button>
  <wc-button type="dashed" status="success">Dashed</wc-button>
  <wc-button type="text" status="success">Text</wc-button>
</wc-space>`;

export const WarningDemo = () => html`<wc-space>
  <wc-button status="warning">Default</wc-button>
  <wc-button type="primary" status="warning">Primary</wc-button>
  <wc-button type="plain" status="warning">Plain</wc-button>
  <wc-button type="dashed" status="warning">Dashed</wc-button>
  <wc-button type="text" status="warning">Text</wc-button>
</wc-space>`;

export const DangerDemo = () => html`<wc-space>
  <wc-button status="danger">Default</wc-button>
  <wc-button type="primary" status="danger">Primary</wc-button>
  <wc-button type="plain" status="danger">Plain</wc-button>
  <wc-button type="dashed" status="danger">Dashed</wc-button>
  <wc-button type="text" status="danger">Text</wc-button>
</wc-space>`;

// docs/zh/demos/button/status.vue
<template>
  <div class="button-display-container">
    <coot-button>Default</coot-button>
    <coot-button type="primary">Primary</coot-button>
    <coot-button type="outline">Outline</coot-button>
    <coot-button type="dashed">Dashed</coot-button>
    <coot-button type="text">Text</coot-button>
    <coot-button type="link">Link</coot-button>
  </div>
  <div class="button-display-container">
    <coot-button status="success">Default</coot-button>
    <coot-button status="success" type="primary">Primary</coot-button>
    <coot-button status="success" type="outline">Outline</coot-button>
    <coot-button status="success" type="dashed">Dashed</coot-button>
    <coot-button status="success" type="text">Text</coot-button>
    <coot-button status="success" type="link">Link</coot-button>
  </div>
  <div class="button-display-container">
    <coot-button status="danger">Default</coot-button>
    <coot-button status="danger" type="primary">Primary</coot-button>
    <coot-button status="danger" type="outline">Outline</coot-button>
    <coot-button status="danger" type="dashed">Dashed</coot-button>
    <coot-button status="danger" type="text">Text</coot-button>
    <coot-button status="danger" type="link">Link</coot-button>
  </div>
  <div class="button-display-container">
    <coot-button status="warning">Default</coot-button>
    <coot-button status="warning" type="primary">Primary</coot-button>
    <coot-button status="warning" type="outline">Outline</coot-button>
    <coot-button status="warning" type="dashed">Dashed</coot-button>
    <coot-button status="warning" type="text">Text</coot-button>
    <coot-button status="warning" type="link">Link</coot-button>
  </div>
</template>

<script setup lang="ts">
import '@coot-ui/button';
</script>

<style scoped lang="less">
.button-display-container {
  display: flex;
  gap: 12px 16px;
  margin-bottom: 16px;
}
</style>
