// packages/wc-design/src/button/demos/status.ts
import { html } from 'lit';
import '../index.ts';
import '../../space';

export const SuccessDemo = () => html`<wc-space>
  <wc-button status="success">Default</wc-button>
  <wc-button type="primary" status="success">Primary</wc-button>
  <wc-button type="plain" status="success">Plain</wc-button>
  <wc-button type="dashed" status="success">Dashed</wc-button>
  <wc-button type="text" status="success">Text</wc-button>
</wc-space>`;

export const WarningDemo = () => html`<wc-space>
  <wc-button status="warning">Default</wc-button>
  <wc-button type="primary" status="warning">Primary</wc-button>
  <wc-button type="plain" status="warning">Plain</wc-button>
  <wc-button type="dashed" status="warning">Dashed</wc-button>
  <wc-button type="text" status="warning">Text</wc-button>
</wc-space>`;

export const DangerDemo = () => html`<wc-space>
  <wc-button status="danger">Default</wc-button>
  <wc-button type="primary" status="danger">Primary</wc-button>
  <wc-button type="plain" status="danger">Plain</wc-button>
  <wc-button type="dashed" status="danger">Dashed</wc-button>
  <wc-button type="text" status="danger">Text</wc-button>
</wc-space>`;

// docs/zh/demos/button/status/index.vue
<template>
  <div class="button-display-container">
    <c-button>Default</c-button>
    <c-button type="primary">Primary</c-button>
    <c-button type="secondary">Secondary</c-button>
    <c-button type="dashed">Dashed</c-button>
    <c-button type="text">Text</c-button>
    <c-button type="link">Link</c-button>
  </div>
  <div class="button-display-container">
    <c-button status="success">Default</c-button>
    <c-button status="success" type="primary">Primary</c-button>
    <c-button status="success" type="secondary">Secondary</c-button>
    <c-button status="success" type="dashed">Dashed</c-button>
    <c-button status="success" type="text">Text</c-button>
    <c-button status="success" type="link">Link</c-button>
  </div>
  <div class="button-display-container">
    <c-button status="error">Default</c-button>
    <c-button status="error" type="primary">Primary</c-button>
    <c-button status="error" type="secondary">Secondary</c-button>
    <c-button status="error" type="dashed">Dashed</c-button>
    <c-button status="error" type="text">Text</c-button>
    <c-button status="error" type="link">Link</c-button>
  </div>
  <div class="button-display-container">
    <c-button status="warning">Default</c-button>
    <c-button status="warning" type="primary">Primary</c-button>
    <c-button status="warning" type="secondary">Secondary</c-button>
    <c-button status="warning" type="dashed">Dashed</c-button>
    <c-button status="warning" type="text">Text</c-button>
    <c-button status="warning" type="link">Link</c-button>
  </div>
</template>

<style scoped lang="less">
.button-display-container {
  display: flex;
  gap: 12px 16px;
  margin-bottom: 16px;
  flex-wrap: wrap;
  &:first-of-type {
    margin-top: 0;
  }
  &:last-of-type {
    margin-bottom: 0;
  }
}
</style>
